"""Rebuilds the "## Example payloads" section of API_CONTRACT.md from ContractTests dumps.

Usage (from frontend/):
  xcodebuild test … -only-testing:SideQuestzTests/ContractTests with TEST_RUNNER_SQ_DUMP_CONTRACT=<dump-dir>
  python3 scripts/gen_contract_examples.py <dump-dir> API_CONTRACT.md
Everything above "## Example payloads" is kept as written.
"""
import json, os, sys

GROUPS = [
    ("Auth", [("SignupRequest", ""), ("AuthResponse", ""), ("UserPatch", "")]),
    ("Me", [("User", ""), ("Preferences", ""), ("TasteProfile", ""), ("Integrations", ""), ("PaymentMethods", "")]),
    ("Facebook (Graph API)", [("FacebookConnection", "GET /integrations/facebook"),
                              ("FacebookImport", "POST /integrations/facebook/import")]),
    ("Calendar + events", [("CalendarDays", ""), ("ItineraryItem", ""), ("TransitOptions", ""),
                           ("SearchResults", "GET /search?q=krog")]),
    ("Planning", [("PlanRequest", ""), ("PlanBatch", ""), ("RouteRequest", ""), ("RouteResult", ""),
                  ("PlanAlternatives", "POST /plans/alternatives"), ("CreateItineraryRequest", "")]),
    ("Itineraries + ratings", [("Itinerary", ""), ("ItineraryUpdate", "PATCH body"), ("PastEvents", ""),
                               ("PastInsights", "GET /me/insights"), ("Rating", ""), ("Ticket", "on a booked item")]),
    ("Checkout", [("CheckoutIntent", "")]),
    ("Forum", [("ForumPosts", ""), ("MyFreePost", ""), ("NewFreePost", "app side of POST /forum/posts"),
               ("JoinResult", "")]),
    ("Threads, album, splits", [("ChatThread", ""), ("Messages", ""), ("Message", "with client_id"),
                                ("GroupPhotos", ""), ("NewExpense", ""), ("GroupLedger", "")]),
    ("Friends", [("Friends", ""), ("FriendRequests", ""),
                 ("OutgoingFriendRequest", "response of POST /friends/requests"), ("UserSearchResults", "")]),
]

dump_dir, contract = sys.argv[1], sys.argv[2]
text = open(contract).read()
marker = "## Example payloads"
head = text[: text.index(marker)]
out = [head, marker, "\n\nGenerated by `ContractTests` from the demo data (`TEST_RUNNER_SQ_DUMP_CONTRACT=<dir>`, then\n"
       "`python3 scripts/gen_contract_examples.py <dir> API_CONTRACT.md`).\n"]
missing = []
for section, items in GROUPS:
    out.append(f"\n### {section}\n")
    for name, note in items:
        path = os.path.join(dump_dir, name + ".json")
        if not os.path.exists(path):
            missing.append(name)
            continue
        body = json.dumps(json.load(open(path)), indent=2, sort_keys=True, ensure_ascii=False)
        label = f"<code>{name}</code>" + (f" ({note})" if note else "")
        out.append(f"\n<details><summary>{label}</summary>\n\n```json\n{body}\n```\n</details>\n")
open(contract, "w").write("".join(out))
unused = sorted(set(f[:-5] for f in os.listdir(dump_dir) if f.endswith(".json")) - {n for _, items in GROUPS for n, _ in items})
print("missing:", missing, "| not shown:", unused)
