package store

import (
	"events/pkg/models"
	"time"
)

// DefaultDemoEvents contains the 25 ticketed events from Saltlight Harbor.
var DefaultDemoEvents = []*models.Event{
	{
		Slug:         "sunset-jazz-on-pier-nine",
		Title:        "Sunset Jazz on Pier Nine",
		Description:  "The Brass Barnacles quartet plays standards as the sun drops behind the moored sailboats. Bring a blanket; the pier bar pours local cider.",
		Summary:      "The Brass Barnacles quartet plays standards as the sun drops behind the moored sailboats.",
		Category:     "live_music",
		Tags:         []string{"outdoor", "cheap", "music", "date", "drinks", "low_energy"},
		Venue:        "Pier Nine Bandstand",
		Address:      "597 Mooring St, Saltlight Harbor, GA 31991",
		Start:        parseTime("2026-09-26T22:30:00Z"),
		End:          parseTime("2026-09-27T01:00:00Z"),
		UnitCents:    1200,
		MaxUnitCents: 2000,
		Capacity:     60,
		Remaining:    60,
		ImageURL:     "https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=800&auto=format&fit=crop",
	},
	{
		Slug:         "barnacle-bash-silent-disco",
		Title:        "Barnacle Bash Silent Disco",
		Description:  "Three headphone channels, three DJs, one echoing drydock. Switch between sea-punk, deep house and 2000s throwbacks until 2 a.m.",
		Summary:      "Three headphone channels, three DJs, one echoing drydock.",
		Category:     "nightclub",
		Tags:         []string{"indoor", "late_night", "music", "high_energy", "group", "21_plus", "drinks"},
		Venue:        "Drydock No. 3",
		Address:      "524 Keel St, Saltlight Harbor, GA 31992",
		Start:        parseTime("2026-09-27T02:00:00Z"),
		End:          parseTime("2026-09-27T06:00:00Z"),
		UnitCents:    1500,
		MaxUnitCents: 2500,
		Capacity:     60,
		Remaining:    60,
		ImageURL:     "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&auto=format&fit=crop",
	},
	{
		Slug:         "seasick-standup-at-the-crow-s-nest",
		Title:        "Seasick Standup at the Crow's Nest",
		Description:  "Saltlight's rowdiest comedy night: five comics, one host in a captain's hat, and a rule that every set must mention a fish.",
		Summary:      "Saltlight's rowdiest comedy night: five comics, one host in a captain's hat, and a rule that every set must mention a fish.",
		Category:     "comedy",
		Tags:         []string{"indoor", "cheap", "late_night", "drinks", "21_plus", "group", "medium_energy"},
		Venue:        "The Crow's Nest",
		Address:      "865 Mooring St, Saltlight Harbor, GA 31991",
		Start:        parseTime("2026-09-27T01:00:00Z"),
		End:          parseTime("2026-09-27T02:40:00Z"),
		UnitCents:    1000,
		MaxUnitCents: 1500,
		Capacity:     60,
		Remaining:    60,
		ImageURL:     "https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=800&auto=format&fit=crop",
	},
	{
		Slug:         "shipyard-robot-regatta",
		Title:        "Shipyard Robot Regatta",
		Description:  "Home-built autonomous boats race a buoy course across the basin. Watch from the seawall or enter your own bot in the open heat at 2 p.m.",
		Summary:      "Home-built autonomous boats race a buoy course across the basin.",
		Category:     "sports_event",
		Tags:         []string{"outdoor", "cheap", "family", "group", "learning", "daytime", "medium_energy"},
		Venue:        "Slipway Basin",
		Address:      "561 Rivet Ave, Saltlight Harbor, GA 31992",
		Start:        parseTime("2026-09-27T17:00:00Z"),
		End:          parseTime("2026-09-27T19:30:00Z"),
		UnitCents:    500,
		MaxUnitCents: 1000,
		Capacity:     60,
		Remaining:    60,
		ImageURL:     "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop",
	},
	{
		Slug:         "harbor-dumpling-brunch-crawl",
		Title:        "Harbor Dumpling Brunch Crawl",
		Description:  "Four stops, four kinds of dumpling: crab soup dumplings, shrimp har gow, pierogi and a dessert bao. Walking pace, ends at the market.",
		Summary:      "Four stops, four kinds of dumpling: crab soup dumplings, shrimp har gow, pierogi and a dessert bao.",
		Category:     "tour",
		Tags:         []string{"outdoor", "food", "group", "daytime", "medium_energy", "local_favorite"},
		Venue:        "Meets at the Fish Box Clock",
		Address:      "750 Stall St, Saltlight Harbor, GA 31994",
		Start:        parseTime("2026-09-27T15:00:00Z"),
		End:          parseTime("2026-09-27T18:00:00Z"),
		UnitCents:    3500,
		MaxUnitCents: 4500,
		Capacity:     60,
		Remaining:    60,
		ImageURL:     "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop",
	},
	{
		Slug:         "paint-the-lighthouse-sip-and-paint",
		Title:        "Paint the Lighthouse: Sip and Paint",
		Description:  "Canvas, brushes and a glass of wine; an instructor walks you through painting the Old Saltlight Lighthouse from the studio window.",
		Summary:      "Canvas, brushes and a glass of wine; an instructor walks you through painting the Old Saltlight Lighthouse from the studio window.",
		Category:     "class_workshop",
		Tags:         []string{"indoor", "art", "date", "drinks", "21_plus", "low_energy", "daytime"},
		Venue:        "Beacon Studio",
		Address:      "628 Lantern Ln, Saltlight Harbor, GA 31990",
		Start:        parseTime("2026-09-27T19:00:00Z"),
		End:          parseTime("2026-09-27T21:00:00Z"),
		UnitCents:    3800,
		MaxUnitCents: 4500,
		Capacity:     60,
		Remaining:    60,
		ImageURL:     "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&auto=format&fit=crop",
	},
	{
		Slug:         "saltlight-mariners-vs-port-coral-fc",
		Title:        "Saltlight Mariners vs. Port Coral FC",
		Description:  "The Mariners host their coastal rivals in the last home match of the season. Supporters' section sings shanties the whole second half.",
		Summary:      "The Mariners host their coastal rivals in the last home match of the season.",
		Category:     "sports_event",
		Tags:         []string{"outdoor", "group", "high_energy", "drinks", "touristy"},
		Venue:        "Mariners Stadium",
		Address:      "51 Sonar Ave, Saltlight Harbor, GA 31993",
		Start:        parseTime("2026-09-27T20:00:00Z"),
		End:          parseTime("2026-09-27T22:00:00Z"),
		UnitCents:    1800,
		MaxUnitCents: 6000,
		Capacity:     60,
		Remaining:    60,
		ImageURL:     "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&auto=format&fit=crop",
	},
	{
		Slug:         "bioluminescence-night-paddle",
		Title:        "Bioluminescence Night Paddle",
		Description:  "Glide through the marsh on a clear-bottom kayak while plankton light up every paddle stroke. Guided, beginner-friendly, limited to 12.",
		Summary:      "Glide through the marsh on a clear-bottom kayak while plankton light up every paddle stroke.",
		Category:     "tour",
		Tags:         []string{"outdoor", "nature", "date", "late_night", "active", "splurge", "medium_energy"},
		Venue:        "Harbor Kayak and SUP",
		Address:      "296 Kelp Rd, Saltlight Harbor, GA 31995",
		Start:        parseTime("2026-09-28T00:00:00Z"),
		End:          parseTime("2026-09-28T02:00:00Z"),
		UnitCents:    4500,
		MaxUnitCents: 5500,
		Capacity:     60,
		Remaining:    60,
		ImageURL:     "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop",
	},
	{
		Slug:         "pop-the-balloon-harbor-speed-friending",
		Title:        "Pop the Balloon: Harbor Speed-Friending",
		Description:  "New in town or just want more crew? Short rounds of conversation, then pop a balloon to reveal your next question. Mocktails included.",
		Summary:      "New in town or just want more crew? Short rounds of conversation, then pop a balloon to reveal your next question.",
		Category:     "community_event",
		Tags:         []string{"indoor", "cheap", "group", "solo_friendly", "medium_energy", "drinks"},
		Venue:        "Market Hall Mezzanine",
		Address:      "506 Stall St, Saltlight Harbor, GA 31994",
		Start:        parseTime("2026-09-27T22:00:00Z"),
		End:          parseTime("2026-09-27T23:30:00Z"),
		UnitCents:    500,
		MaxUnitCents: 500,
		Capacity:     60,
		Remaining:    60,
		ImageURL:     "https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800&auto=format&fit=crop",
	},
	{
		Slug:         "drag-brunch-ahoy",
		Title:        "Drag Brunch Ahoy!",
		Description:  "Mermaid-themed drag numbers, bottomless mimosas and a crab-cake benedict. Reservations fill up; tips go to the queer youth sailing club.",
		Summary:      "Mermaid-themed drag numbers, bottomless mimosas and a crab-cake benedict.",
		Category:     "theater",
		Tags:         []string{"indoor", "food", "drinks", "21_plus", "group", "high_energy", "daytime"},
		Venue:        "Siren Song Lounge",
		Address:      "230 Marina Row, Saltlight Harbor, GA 31991",
		Start:        parseTime("2026-09-27T16:00:00Z"),
		End:          parseTime("2026-09-27T18:00:00Z"),
		UnitCents:    3500,
		MaxUnitCents: 4500,
		Capacity:     60,
		Remaining:    60,
		ImageURL:     "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800&auto=format&fit=crop",
	},
	{
		Slug:         "boardwalk-pickleball-round-robin",
		Title:        "Boardwalk Pickleball Round-Robin",
		Description:  "Paddles provided, partners assigned. Fast games, a leaderboard, and lemonade for the winners.",
		Summary:      "Paddles provided, partners assigned.",
		Category:     "community_event",
		Tags:         []string{"outdoor", "cheap", "active", "group", "daytime", "medium_energy"},
		Venue:        "Boardwalk Courts",
		Address:      "615 Gull Way, Saltlight Harbor, GA 31997",
		Start:        parseTime("2026-09-27T18:30:00Z"),
		End:          parseTime("2026-09-27T20:30:00Z"),
		UnitCents:    800,
		MaxUnitCents: 800,
		Capacity:     60,
		Remaining:    60,
		ImageURL:     "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800&auto=format&fit=crop",
	},
	{
		Slug:         "beginner-arduino-build-a-tide-sensor",
		Title:        "Beginner Arduino: Build a Tide Sensor",
		Description:  "Wire up an ultrasonic sensor and log real water levels from the dock. Kit included and yours to keep. No experience needed.",
		Summary:      "Wire up an ultrasonic sensor and log real water levels from the dock.",
		Category:     "class_workshop",
		Tags:         []string{"indoor", "cheap", "learning", "solo_friendly", "medium_energy"},
		Venue:        "The Shipyard Makerspace",
		Address:      "255 Rivet Ave, Saltlight Harbor, GA 31992",
		Start:        parseTime("2026-09-28T22:00:00Z"),
		End:          parseTime("2026-09-29T00:30:00Z"),
		UnitCents:    2500,
		MaxUnitCents: 2500,
		Capacity:     60,
		Remaining:    60,
		ImageURL:     "https://images.unsplash.com/photo-1553406830-ef2513450d76?w=800&auto=format&fit=crop",
	},
	{
		Slug:         "moonlight-yoga-on-lanternfall-beach",
		Title:        "Moonlight Yoga on Lanternfall Beach",
		Description:  "A gentle flow on the sand under the rising moon. Mats available to borrow; ends with a guided breathing session to the sound of the surf.",
		Summary:      "A gentle flow on the sand under the rising moon.",
		Category:     "class_workshop",
		Tags:         []string{"outdoor", "cheap", "low_energy", "solo_friendly", "nature"},
		Venue:        "Lanternfall Beach",
		Address:      "123 Gull Way, Saltlight Harbor, GA 31997",
		Start:        parseTime("2026-09-28T23:30:00Z"),
		End:          parseTime("2026-09-29T00:30:00Z"),
		UnitCents:    1000,
		MaxUnitCents: 1000,
		Capacity:     60,
		Remaining:    60,
		ImageURL:     "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&auto=format&fit=crop",
	},
	{
		Slug:         "coral-reef-restoration-dive",
		Title:        "Coral Reef Restoration Dive",
		Description:  "Certified divers help plant coral fragments on the Saltlight artificial reef. Snorkelers can help from the surface. Gear rental included.",
		Summary:      "Certified divers help plant coral fragments on the Saltlight artificial reef.",
		Category:     "community_event",
		Tags:         []string{"outdoor", "active", "nature", "high_energy", "group", "daytime"},
		Venue:        "Reef Station Dock",
		Address:      "456 Coral Rd, Saltlight Harbor, GA 31996",
		Start:        parseTime("2026-09-29T12:00:00Z"),
		End:          parseTime("2026-09-29T16:00:00Z"),
		UnitCents:    3000,
		MaxUnitCents: 3000,
		Capacity:     60,
		Remaining:    60,
		ImageURL:     "https://images.unsplash.com/photo-1544551763-77ef2d0cfc6c?w=800&auto=format&fit=crop",
	},
	{
		Slug:         "karaoke-night-at-the-fish-box",
		Title:        "Karaoke Night at the Fish Box",
		Description:  "Main-stage karaoke with a light-up fish-crate stage. Sea-song duets get a free round.",
		Summary:      "Main-stage karaoke with a light-up fish-crate stage.",
		Category:     "bar",
		Tags:         []string{"indoor", "cheap", "music", "drinks", "late_night", "group", "high_energy"},
		Venue:        "Fish Box Karaoke",
		Address:      "675 Brine Ave, Saltlight Harbor, GA 31994",
		Start:        parseTime("2026-09-30T01:00:00Z"),
		End:          parseTime("2026-09-30T04:00:00Z"),
		UnitCents:    500,
		MaxUnitCents: 1000,
		Capacity:     60,
		Remaining:    60,
		ImageURL:     "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&auto=format&fit=crop",
	},
	{
		Slug:         "chef-s-table-seven-courses-of-the-sea",
		Title:        "Chef's Table: Seven Courses of the Sea",
		Description:  "Chef Ines Marlow cooks seven courses from that morning's catch at a twelve-seat counter. Wine pairing optional.",
		Summary:      "Chef Ines Marlow cooks seven courses from that morning's catch at a twelve-seat counter.",
		Category:     "restaurant",
		Tags:         []string{"indoor", "splurge", "food", "date", "drinks", "low_energy"},
		Venue:        "The Captain's Table",
		Address:      "334 Marina Row, Saltlight Harbor, GA 31991",
		Start:        parseTime("2026-09-29T23:00:00Z"),
		End:          parseTime("2026-09-30T01:30:00Z"),
		UnitCents:    12000,
		MaxUnitCents: 15000,
		Capacity:     60,
		Remaining:    60,
		ImageURL:     "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop",
	},
	{
		Slug:         "kids-shipwright-workshop-cardboard-boats",
		Title:        "Kids' Shipwright Workshop: Cardboard Boats",
		Description:  "Kids design and tape together a cardboard boat, then test it in the float tank. Ages 6-12 with a grown-up.",
		Summary:      "Kids design and tape together a cardboard boat, then test it in the float tank.",
		Category:     "class_workshop",
		Tags:         []string{"indoor", "cheap", "family", "learning", "daytime", "medium_energy"},
		Venue:        "The Shipyard Makerspace",
		Address:      "255 Rivet Ave, Saltlight Harbor, GA 31992",
		Start:        parseTime("2026-09-30T20:00:00Z"),
		End:          parseTime("2026-09-30T21:30:00Z"),
		UnitCents:    800,
		MaxUnitCents: 800,
		Capacity:     60,
		Remaining:    60,
		ImageURL:     "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop",
	},
	{
		Slug:         "xr-art-night-paint-in-virtual-waves",
		Title:        "XR Art Night: Paint in Virtual Waves",
		Description:  "Sculpt glowing sea creatures in 3D with VR brushes and take home a video of your piece. Headsets provided.",
		Summary:      "Sculpt glowing sea creatures in 3D with VR brushes and take home a video of your piece.",
		Category:     "class_workshop",
		Tags:         []string{"indoor", "cheap", "art", "learning", "date", "medium_energy"},
		Venue:        "The Lighthouse Laboratory",
		Address:      "195 Beacon Way, Saltlight Harbor, GA 31990",
		Start:        parseTime("2026-09-30T23:00:00Z"),
		End:          parseTime("2026-10-01T01:00:00Z"),
		UnitCents:    1500,
		MaxUnitCents: 1500,
		Capacity:     60,
		Remaining:    60,
		ImageURL:     "https://images.unsplash.com/photo-1535223289827-42f1e9919769?w=800&auto=format&fit=crop",
	},
	{
		Slug:         "oyster-shucking-101",
		Title:        "Oyster Shucking 101",
		Description:  "Learn to open, grade and slurp three local varieties. Every student leaves with a shucking knife.",
		Summary:      "Learn to open, grade and slurp three local varieties.",
		Category:     "class_workshop",
		Tags:         []string{"indoor", "food", "learning", "drinks", "group", "medium_energy"},
		Venue:        "Brine and Bivalve Oyster Bar",
		Address:      "810 Stall St, Saltlight Harbor, GA 31994",
		Start:        parseTime("2026-10-01T22:30:00Z"),
		End:          parseTime("2026-10-02T00:00:00Z"),
		UnitCents:    3500,
		MaxUnitCents: 3500,
		Capacity:     60,
		Remaining:    60,
		ImageURL:     "https://images.unsplash.com/photo-1534482421-64566f976cfa?w=800&auto=format&fit=crop",
	},
	{
		Slug:         "the-tempest-at-the-tidewater-playhouse",
		Title:        "The Tempest at the Tidewater Playhouse",
		Description:  "Shakespeare's shipwreck comedy staged with real rigging and a water tank at the front of the stage. The first two rows may get wet.",
		Summary:      "Shakespeare's shipwreck comedy staged with real rigging and a water tank at the front of the stage.",
		Category:     "theater",
		Tags:         []string{"indoor", "art", "date", "low_energy"},
		Venue:        "Tidewater Playhouse",
		Address:      "662 Lantern Ln, Saltlight Harbor, GA 31990",
		Start:        parseTime("2026-10-01T23:30:00Z"),
		End:          parseTime("2026-10-02T02:00:00Z"),
		UnitCents:    2500,
		MaxUnitCents: 6000,
		Capacity:     60,
		Remaining:    60,
		ImageURL:     "https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=800&auto=format&fit=crop",
	},
	{
		Slug:         "deep-house-at-the-deep-end",
		Title:        "Deep House at the Deep End",
		Description:  "Resident DJs play underwater-themed deep house under a ceiling of blue light. Doors at 10, peak around 1.",
		Summary:      "Resident DJs play underwater-themed deep house under a ceiling of blue light.",
		Category:     "nightclub",
		Tags:         []string{"indoor", "late_night", "music", "high_energy", "21_plus", "drinks"},
		Venue:        "The Deep End",
		Address:      "24 Fathom St, Saltlight Harbor, GA 31993",
		Start:        parseTime("2026-10-02T02:00:00Z"),
		End:          parseTime("2026-10-02T07:00:00Z"),
		UnitCents:    2000,
		MaxUnitCents: 3000,
		Capacity:     60,
		Remaining:    60,
		ImageURL:     "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&auto=format&fit=crop",
	},
	{
		Slug:         "friday-fish-fry-and-bluegrass",
		Title:        "Friday Fish Fry and Bluegrass",
		Description:  "Fried catfish, hushpuppies and slaw, with the Heron Creek Pickers on the porch stage. Kids eat free.",
		Summary:      "Fried catfish, hushpuppies and slaw, with the Heron Creek Pickers on the porch stage.",
		Category:     "live_music",
		Tags:         []string{"outdoor", "cheap", "food", "music", "family", "group", "medium_energy"},
		Venue:        "Kelp Hollow Pavilion",
		Address:      "495 Heron Ct, Saltlight Harbor, GA 31995",
		Start:        parseTime("2026-10-02T22:00:00Z"),
		End:          parseTime("2026-10-03T01:00:00Z"),
		UnitCents:    1500,
		MaxUnitCents: 1500,
		Capacity:     60,
		Remaining:    60,
		ImageURL:     "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop",
	},
	{
		Slug:         "lantern-festival-on-the-water",
		Title:        "Lantern Festival on the Water",
		Description:  "Decorate a paper lantern, write a wish on it and float it out at dusk. Food trucks and taiko drummers line the beach.",
		Summary:      "Decorate a paper lantern, write a wish on it and float it out at dusk.",
		Category:     "festival",
		Tags:         []string{"outdoor", "cheap", "family", "date", "touristy", "low_energy"},
		Venue:        "Lanternfall Beach",
		Address:      "123 Gull Way, Saltlight Harbor, GA 31997",
		Start:        parseTime("2026-10-02T22:00:00Z"),
		End:          parseTime("2026-10-03T03:00:00Z"),
		UnitCents:    500,
		MaxUnitCents: 500,
		Capacity:     60,
		Remaining:    60,
		ImageURL:     "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&auto=format&fit=crop",
	},
	{
		Slug:         "retro-sea-monster-arcade-tournament",
		Title:        "Retro Sea Monster Arcade Tournament",
		Description:  "Bracket play on a cabinet game about giant squid. Unlimited free play on the rest of the floor with entry.",
		Summary:      "Bracket play on a cabinet game about giant squid.",
		Category:     "rec_venue",
		Tags:         []string{"indoor", "cheap", "late_night", "group", "high_energy"},
		Venue:        "Pixel Pier Arcade",
		Address:      "470 Fathom St, Saltlight Harbor, GA 31993",
		Start:        parseTime("2026-10-03T01:00:00Z"),
		End:          parseTime("2026-10-03T04:00:00Z"),
		UnitCents:    1000,
		MaxUnitCents: 1000,
		Capacity:     60,
		Remaining:    60,
		ImageURL:     "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&auto=format&fit=crop",
	},
	{
		Slug:         "sustainable-seafood-cooking-class",
		Title:        "Sustainable Seafood Cooking Class",
		Description:  "Cook three dishes from overlooked, sustainable species. Includes dinner and a guide to buying fish responsibly at the market.",
		Summary:      "Cook three dishes from overlooked, sustainable species.",
		Category:     "class_workshop",
		Tags:         []string{"indoor", "food", "learning", "date", "splurge", "medium_energy"},
		Venue:        "Market Hall Test Kitchen",
		Address:      "797 Brine Ave, Saltlight Harbor, GA 31994",
		Start:        parseTime("2026-10-02T21:30:00Z"),
		End:          parseTime("2026-10-03T00:00:00Z"),
		UnitCents:    5500,
		MaxUnitCents: 5500,
		Capacity:     60,
		Remaining:    60,
		ImageURL:     "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&auto=format&fit=crop",
	},
}

func parseTime(rfc3339 string) time.Time {
	t, _ := time.Parse(time.RFC3339, rfc3339)
	return t
}
